
export const essayRoy = {
    'label': 'III',
    'title': '(Other)worldly Things: The Social and Material Lives of Photographs in Southeast Asia',
    'subtitle': 'Roy Ng, Assistant Curator at National Gallery Singapore',
    'abstract': 'Excerpt from "(Other)worldly Things: The Social and Material Lives of Photographs in Southeast Asia" in Living Pictures (2022) edited by Charmaine Toh. Available for access in its entirety, on Project Muse and JSTOR.',
    'markdown': `
The photograph is, in the most fundamental sense of the word, a thing. It is created, dispersed, kept, relocated and stored for purposes which do not necessarily coincide, sometimes appearing torn, scratched or cropped depending on how it is used.  Rather than simply defined by its two-dimension-ality, it is also tied inescapably to space and time. The photograph is more than a depictive device; it is entangled in everyday life—its physical, tactile and often opaque quality renders it a subject of daily interaction. While the act of engaging with a photograph invariably exposes it to the rough and tumble of reality, the same photograph also helps to construct that same reality—it engenders not a passive text but rather an active dialogue, a locus for a collective show-and-tell. Simultaneously, the transparency of the medium compels a kind of self-deception on the part of the viewer—“in order to see what the photograph is ‘*of*’ we must first suppress our consciousness of what the photograph ‘*is*’ in material terms.” [^1] To immerse ourselves in the world of the image, we need to detach ourselves from the photograph’s physical properties and the print we are holding and beholding. Materiality, in this regard, is often glossed over as a neutral, unobtrusive support for the picture, such that we may try to absorb ourselves into that which is depicted—to move beyond the picture plane to forge a kind of bond with the portrayed (and sometimes revered) subject. [^2]
Such visual negotiation is all the more pertinent in the context of royal and religious devotion in Southeast Asia. Rather than deflecting or demystifying the aura embedded in the image, the photograph augments that same aura with a tangible and earthly identity, reifying the image’s visual and spiritual presence to the point where it becomes physical and almost equivalent to any other everyday object. The photograph, in keeping with its objecthood, exists as a paradox: it is through the print’s “worldliness” that the gaze may be transported towards the “otherworldly” dimension of the image. This essay assesses the social and material functions of photographs in Southeast Asia by paying particular attention to works that operate as images for visual commemoration, devotion and worship, because of and not despite the fact that they are objects. It aims to explore this notion through the prism of portraiture—specifically the royal portraits in Thailand, images of patriarchs and matriarchs in Straits Chinese ancestral halls, and the monastic prints of Buddhadasa Bhikkhu (1906–1993) and Manit Sriwanichpoom (b. 1961). Perhaps, rather than seeing objecthood as being antithetical to the image, we may find a kind of ironic compromise, where the medium offers access to the message precisely because of the photograph’s social and material qualities. We enter, through the world of the humble print, into an otherworld.

## ROYAL PORTRAITS

Unlike the rest of late 19<sup>th</sup> century Southeast Asia, which was marked by the cultural conditions of colonialism, photography in Thailand was a technology that was indigenised and appropriated as a tool for the fashioning of a people’s monarchy. Before the advent of photography, images of royalty revolved around Indo-Buddhist notions of *devaraja* and *dhammaraja* (divine and moral kingship), where the monarch was sacred to the extent that he was remote from the public eye. [^3] Commoners were expected to lower their gaze during royal processions and foreign envoys were prohibited from looking directly at the sovereign during royal audiences. The monarchy was nearly devoid of pictorial representation; even after death, images of the Buddha were used instead of a monarch’s visage to commemo-rate the king. [^4] Royal portraiture was by and large absent before the mid-19<sup>th</sup> century. With the arrival of the camera in Thailand around that time, photographic objects circulated widely and were soon appropriated as new symbols of the modern state. Such demands paralleled a shift in cultural values amongst the Thai royals and aristocrats who had, according to historian Maurizio Peleggi, embraced photography as a mode of portraiture now that they had “re-oriented their social identity from the civilisational sphere irradiating from India, and to a lesser extent China, to one centred in Europe.” [^5] The real-ism of photography embodied, for these Thai elites, a certain allure—the camera symbolised what they perceived as among the most advanced products of Western culture and technology, where representational power seemed to resonate with the political might of imperialism. 

Examples of this notion include the portraits of King Chulalongkorn, Rama V (r. 1868–1910), one of the most photographed monarchs in the 19<sup>th</sup> century and an avid photographer in his later years. A portrait, taken on his second coronation in October 1873 (*see* {% cite 'pl. 104' %}), reveals the new king’s desire to harness the magic of photographic reproduction. In this albumen silver print produced by Thai court photographer Francis Chit (1830–1891) in 1873, the monarch is seated in his royal regalia. His front-facing posture and stately pose create a symmetrical composition only to be broken slightly by a sword which he wields as if it were a godly attribute. One could read this as a mode of royal legitimisation, a visual proclamation of Rama V’s right to inherit the throne. [^6] The stern composition of the image is reminiscent of Hindu-Buddhist iconography—from the king’s crown at the centre, the fruit bowl on the left and the urn on the right, we see a triadic arrangement befitting of, and alluding to, the *devaraja*. Contrast that with the photograph of Rama V taken by Prussian photographer Robert Lenz (1864–1939) before the king left for his first journey to Europe in April 1897. 

{% figure 'hr' %}
{% figure 'fig-2' %}
{% figure 'hr' %}

In this case, the king emulates Western conventions of royal portraiture: Rama V is dressed in a Napoleonic garment with a robe flowing across his shoulder, with the studio’s interior décor resembling a salon. Lenz’s work transposes the well-known visual norms of royal portraiture under the camera’s lens, cropping the regal aura of the image to fit into photography’s vernacular. By domesticating the status of kingship within the print’s representational space, he confers the idea that the king can be looked upon in private, domestic settings. [^7]

While originally produced for visual consumption by the Thai elite and Western expatriates, these photographs occasionally circulated as postcards and illustrations in books and magazines for a mass audience in Thailand. Towards the latter part of Rama V’s reign, his face was even embossed on coins and printed on stamps, and his equestrian statue was erected to oversee Bangkok’s public space, as was the civil model and convention in Thailand’s neighbouring colonies under European rule. [^8] It is from such an unprecedented scale of reproducing the king’s likeness that one might then speculate a withering of his royal aura. His image, to use German philosopher Walter Benjamin’s term, is subject to the onslaught of mechanical reproduction, and the authoritative, authentic and aesthetic presence of the original—that single definitive encounter with the king—is eroded. [^9] Through the photographic medium, the original is displaced by the ubiquitous copy, embedded in a process of mass circulation. The “reproduced” monarch, according to historian H.G. Quaritch Wales, far from being reduced to an everyday commodity, is transformed into a historical subject. Likewise, the king, insofar as he is a symbol of “perennial” or “eternal” Buddhist values, could also be a product of changing times. [^10] If reproduction was a force to be reckoned with, the point then, at least for Rama V’s court, was not to deny it, but to use it. More than just the image, the process with which it was dispersed became in and of itself a mode of self-fashioning, positioning Rama V as a forward-looking sovereign attuned to flux and receptive to the speed of modernity.

In this regard, the photographic object both entrenches and disrupts this historically bound conception of royalty, shifting the relational dynamic between king and Siamese subject towards one that occurs within a space of intimate devotion. Now a presiding figure in each household or one’s private possession, the royal image is assumed to be anywhere and everywhere, his omnipresence buttressed by modern modes of reproduction. What emerges could well be a type of *buzz*, to use art historian David Joselit’s term, where under the purview of the king’s photographers and their studios, reproductive behaviours are coordinated to exalt the monarch’s presence in newly inventive ways. [^11] The velocity and commercial mobility of *all* royal portraits might be regarded as constituent parts in an ever-expanding economy of images, existing in a constant state of becoming. Reproduction, far from negating the monarch’s allure, reifies his image as a progressive figure. With the endless potential of copying and dispersing his portrait, the royal presence could be seen as extending beyond the strict confines of the court, to “touch” the subject through private or public moments of viewing, and vice versa. It is through the photograph as *object* that the king appears before his subject—not in the flesh, but a close equivalent of it through print, to be seen and held by the beholder. Represented, collected, distributed and displayed as didactic expressions of ideal leadership, the monarch resides in a variable, liminal and contingent space existing here and now as much as he does *there and then*. [^12] 
  `,
  'endNotes': [
    'Geoffrey Batchen, *Photography’s Objects* (Albuquerque: University of New Mexico Art Museum, 1997), 2.',
    'Elizabeth Edards & Janice Hart, “Photograph as Objects,” in *Photographs, Objects, Histories: On the Materiality of Images*, eds. Elizabeth Edwards & Janice Hart (London: Routledge, 2004), 2.',
    'Maurizio Peleggi, “The Aesthetics and Politics of Royal Portraiture in Thailand,” *Ars Orientalis* 43 (2013): 84.',
    'Apinan Poshyananda, *Chittrakam lae patimakam baep tawantok nai racthasanmak* (Western-Style Painting and Sculpture in the Thai Royal Court), vol. 1 (Bangkok: Bureau of the Royal Household, 1992), 336.',
    'Maurizio Peleggi, *Lord of Things: The Fashioning of the Siamese Monarchy’s Modern Image* (Ho-nolulu: University of Hawaii Press, 2002), 11–14.',
    'Peleggi, “Aesthetics and Politics,” 87.',
    'Ibid., 88.',
    'Ibid.',
    'Walter Benjamin, “The Work of Arin the Age of Mechanical Repro-duction” in *Illuminations: Essays and Reflections*, trans. Harry Zohn (New York: Schocken Books, 1968), 217–251.',
    'H.G. Quaritch Wales, *Siamese State Ceremonies* (London: B. Quaritch, 1931), 173.',
    'D. Joselit, *After Art* (Princeton: Princeton University Press, 2013), 15–16.',
    'Joanna Wolfarth, “Royal Portraiture in the Cambodian Politico-Cultural Complex: Norodom Sihanouk and the Place of Photography,” *Udaya: Journal of Khmer Studies* 12 (2014): 145, 163.',
  ],
};
