
export const forewordMainText = `
National Gallery Singapore is proud to present Living Pictures: Photography in Southeast Asia, a groundbreaking exhibition of photographs by artists working in and from Southeast Asia. Living Pictures represents the Gallery’s first foray into writing a regional history of photography, the culmination of years of thought, research and care into crafting a narrative of great significance to our understanding of global art histories.

Photography has thus far been included in the art histories of Southeast Asia in minor, even incidental, ways, ill befitting of the power of the medium, perspective of the photographers and influence of the images produced. Its exclusion from predominant art historical narratives could well be due to the complex nature of photographs themselves, tied up simultaneously as a mode of documentation and artistic production. The potential of the medium gives rise to inherent contradictions that might be perceived as obstacles to a singular, coherent narrative.

Living Pictures confronts the complexities of photography head-on. It traverses the character of each individual image to take a wider view of photography, shifting the general tenor of discussion on photography beyond the framework established by the chronological analysis of stylistic development particular to the formation of the Western photographic canon, focussing instead on the function of these photographs. Lines of inquiry explored both in the exhibition and this catalogue evolve from the notion that photographs have and continue to play a role in how we see the world and therefore shape it: what do photographs do?

Living Pictures responds to five key themes that have emerged over the course of research, elaborated upon in detail in this catalogue by forerunners in the work on photography in Southeast Asia. Each section of this book, introduced by lead curator Charmaine Toh, illustrates the power and influence of photography: from its effect on the colonial imagination and formation of certain identities to present-day effects of the blitz of photographic images in our daily lives. The exhibition and catalogue both highlight the place of photography in art history, but as its title suggests, the changing uses of photographs—perhaps even the changing narrative of a single photograph—reveal their relevance to the way we see and interact with our world today.

That the Gallery is actively rewriting the histories of global art through the perspective of Southeast Asian art histories is no small feat; unreserved thanks is given to our colleagues, including exhibition curators Roger Nelson, Goh Sze Ying, Roy Ng and Kenneth Tay, who are dedicated to uncovering these marginalised narratives that we hope will make a great impact on the art historical canon. We are also grateful to the individuals and institutions who have generously lent us their works for this display, allowing our publics this significant access. We hope the many lives of photographs might inspire new reflections on the medium, and much more exciting possibilities to come.
`
