name: Build Docker Image

on:
  push:
    branches:
      - master
      - feature/ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image and push to Docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t michac789/ngs-living-pictures:latest -f Dockerfile.prod .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push michac789/ngs-living-pictures:latest
