name: Deploy Application CI/CD

on:
  push:
    branches:
      - master
      - feature/ci-cd

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image and push to Docker hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker build -t michac789/ngs-living-pictures:latest -f Dockerfile.prod .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push michac789/ngs-living-pictures:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_SSH_USER }}
          key: ${{ secrets.DROPLET_SSH_PRIVATE_KEY }}
          passphrase: ${{ secrets.DROPLET_SSH_PASSPHRASE }}
          script: |
            docker stop ngs-web
            docker rm ngs-web
            docker rmi michac789/ngs-living-pictures:latest
            docker pull michac789/ngs-living-pictures:latest
            docker run -d -p 3200:3000 --name ngs-web michac789/ngs-living-pictures:latest
